// <auto-generated />
using System;
using BlazorAppNotes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorAppNotes.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231008223037_updateDefaultData")]
    partial class updateDefaultData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorAppNotes.Data.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("NoteId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Content 1",
                            CreatedDate = new DateTime(2023, 10, 8, 22, 30, 37, 567, DateTimeKind.Utc).AddTicks(6009),
                            Title = "Title 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Content 2",
                            CreatedDate = new DateTime(2023, 10, 8, 22, 30, 37, 567, DateTimeKind.Utc).AddTicks(6012),
                            Title = "Title 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Content 3",
                            CreatedDate = new DateTime(2023, 10, 8, 22, 30, 37, 567, DateTimeKind.Utc).AddTicks(6013),
                            Title = "Title 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Content 4",
                            CreatedDate = new DateTime(2023, 10, 8, 22, 30, 37, 567, DateTimeKind.Utc).AddTicks(6015),
                            Title = "Title 4"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Content 5",
                            CreatedDate = new DateTime(2023, 10, 8, 22, 30, 37, 567, DateTimeKind.Utc).AddTicks(6016),
                            Title = "Title 5"
                        },
                        new
                        {
                            Id = 6,
                            Content = "Content 6",
                            CreatedDate = new DateTime(2023, 10, 8, 22, 30, 37, 567, DateTimeKind.Utc).AddTicks(6018),
                            Title = "Title 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
